/* $OpenBSD: version.h,v 1.102 2024/07/01 04:31:59 djm Exp $ */

#define SSH_WINDOWS_VERSION "OpenSSH_for_Windows_9.8"
#define SSH_WINDOWS_BANNER " Win32-OpenSSH-GitHub"
#define SSH_VERSION	SSH_WINDOWS_VERSION SSH_WINDOWS_BANNER

#define SSH_PORTABLE	"p1"
#define SSH_RELEASE	SSH_WINDOWS_VERSION SSH_PORTABLE SSH_WINDOWS_BANNER
