set(VCPKG_TARGET_ARCHITECTURE arm)
set(VCPKG_ENV_PASSTHROUGH "__VSCMD_ARG_WINSDK;__VCVARSALL_SPECTRE")
set(VCPKG_CXX_FLAGS "/Qspectre")
set(VCPKG_C_FLAGS "/Qspectre")
set(VCPKG_LINKER_FLAGS "/guard:cf /DYNAMICBASE")

if(${PORT} MATCHES "libressl")
	set(VCPKG_CRT_LINKAGE dynamic)
	set(VCPKG_LIBRARY_LINKAGE dynamic)
else()
	set(VCPKG_CRT_LINKAGE static)
	set(VCPKG_LIBRARY_LINKAGE static)
endif()

if(${PORT} MATCHES "zlib")
	set(VCPKG_CXX_FLAGS "${VCPKG_C_FLAGS} /sdl")
	set(VCPKG_C_FLAGS "${VCPKG_C_FLAGS} /sdl")
endif()
